apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy70
  labels:
    app: autodeploy70
  namespace: namespace-workflow-1705563160829
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy70
  template:
    metadata:
      labels:
        app: autodeploy70
    spec:
      containers:
        - name: autodeploy70
          image: acrworkflow1705563160829.azurecr.io/image-workflow-1705563160829:latest
          ports:
            - containerPort: 5000