apiVersion: v1
kind: Service
metadata:
  name: autodeploy70
  namespace: namespace-workflow-1705563160829
spec:
  type: LoadBalancer
  selector:
    app: autodeploy70
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000